### ISSUE TITLE
To Eve or not to Eve

### ISSUE THREAD

**Issue by DraTeots** [JeffersonLab/HDvis#1]
That is the question

I put here updates on mails to other EVE users

**Comment by DraTeots** [comment]
Since the idea is to proof that EVE is not abandoned at all. Here is GitHub pages that shows the activity:

[Tutorials](https://github.com/root-project/root/tree/4fa59f4fb80fd914cb84144e5218e55397810c01/tutorials/eve) 
are updated like 7 months ago but there wasn't any significant changes 

[Code](https://github.com/root-project/root/tree/4fa59f4fb80fd914cb84144e5218e55397810c01/graf3d/eve/src) - looks like it hasn't been much reviewed from 2009 or so

[Some interesting file](https://github.com/root-project/root/commits/4fa59f4fb80fd914cb84144e5218e55397810c01/graf3d/eve/src/TEveTrackPropagator.cxx) - the idea here, is that this class is not just like dumb wrapper and it has the last bug fix from 2013. Maybe that is ok.

**Comment by T-Britton** [comment]
We eve'd.
